apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-prod
  namespace: production
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/databases/redis-db'