apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: '/databases/mongo-db'
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc-prod
  replicas: 1