apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-prod
  namespace: production
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/databases/mongo-db'