apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-dev
  namespace: development
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/databases/mongo-db'