apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: development
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: '/databases/redis-db'
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis-pvc-dev
  replicas: 1